version: '3.9'
services:
  postgres-comments:
    container_name: postgres-comments
    image: postgres:latest
    hostname: database
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=comments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - keycloak_demo
  backend-web:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - FRONTEND_URL=http://45.139.77.150:3000
    container_name: backend-web
    networks:
      - keycloak_demo
    ports:
      - "8080:8080"
  react:
    container_name: react
    build: ./webTask
    environment:
      - BACK_URL=http://45.139.77.150:8080
    ports:
      - "3000:3000"

networks:
  keycloak_demo:
    driver: bridge
