version: '3.9'
services:
  # Сервис для разворачивания контейнера с базой данных  
  postgres-comments:
    container_name: postgres-comments
    image: postgres:latest
    hostname: database
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=comments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - keycloak_demo
  backend-web:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: backend-web
    networks:
      - keycloak_demo
    ports:
      - "8080:8080"
  react:
    container_name: react
    build: ./webTask
    environment:
      - HTTPS=true
      - SSL_CRT_FILE=/app/certs/fullchain.pem
      - SSL_KEY_FILE=/app/certs/privkey.pem
    ports:
      - "3000:3000"

networks:
  keycloak_demo:
    driver: bridge
