server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-comments:5432/comments
    username: admin
    password: password
  flyway:
    enabled: true
    locations:
      - db.migration
    baseline-on-migrate: true
