

spring:
  datasource:
    url: jdbc:postgresql://postgres-comments:5432/comments
    username: admin
    password: password
  flyway:
    enabled: true
    locations:
      - db.migration
    baseline-on-migrate: true

server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    # The path to the keystore containing the certificate
    key-store: ./keystore.p12
    # The password used to generate the certificate
    key-store-password: password
    # The alias mapped to the certificate
    key-alias: tomcat
